on: push

name: CI/CD

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          nix_archives_url: https://github.com/nixbuild/nix-quick-install-action/releases/download/v0
          nix_version: 3.0pre20200829_f156513
          nix_conf: experimental-features = nix-command flakes
      - name: Build nix archives
        id: build-nix-archives
        run: |
          nix build .#nix-archives
          echo "::set-output name=result::$(readlink result)"
      - uses: actions/upload-artifact@v2
        with:
          name: nix-archives
          path: ${{ steps.build-nix-archives.outputs.result }}/

  test-nix:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        nix_version:
          - 3.0pre20200829_f156513
          - 2.3.7
          - 2.2.2
          - 2.1.3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        id: nix-archives
        with:
          name: nix-archives
      - uses: ./
        with:
          nix_archives_url: file://${{steps.nix-archives.outputs.download-path}}
          nix_version: ${{ matrix.nix_version }}
      - name: Test nix
        run: nix-build -v --version

  test-cachix:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        id: nix-archives
        with:
          name: nix-archives
      - uses: ./
        with:
          nix_archives_url: file://${{steps.nix-archives.outputs.download-path}}
          nix_version: 3.0pre20200829_f156513
          nix_conf: experimental-features = nix-command flakes
      - uses: cachix/cachix-action@v6
        with:
          name: nixbuild
          signingKey: ${{ secrets.cachix_signing_key }}
      - name: Verify nix config
        run: |
          nix show-config > nix.conf
          cat nix.conf
          if ! egrep -q "^substituters = https://cache.nixos.org https://nixbuild.cachix.org$" nix.conf; then
            echo "Invalid substiturers config"
            exit 1
          fi
      - name: Push to Cachix
        id: push-to-cachix
        run: |
          dd if=/dev/urandom of=random count=1
          echo ::set-output name=hash "$(nix add-to-store random | sed 's,^/nix/store/\(.*\)-random$,\1,g')"
      - name: Query Cachix
          curl --fail -sL "https://nixbuild.cachix.org/${{ steps.push-to-cachix.outputs.hash }}.narinfo"


  release:
    runs-on: ubuntu-latest
    needs:
      - build
      - test-nix
      - test-cachix
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        id: nix-archives
        with:
          name: nix-archives
      - uses: ./
        with:
          nix_archives_url: file://${{steps.nix-archives.outputs.download-path}}
          nix_version: 3.0pre20200829_f156513
          nix_conf: experimental-features = nix-command flakes
      - name: Build release script
        run: nix build .#release
      - name: Release if needed
        run: ./result/bin/release ${{steps.nix-archives.outputs.download-path}} ./RELEASE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
